import os

HERE = os.path.dirname(__file__)
DEBUG = True
REDIS_HOST = 'localhost'
REDIS_PORT = 6379

SERVER_PUBLIC_KEY = u'-----BEGIN RSA PUBLIC KEY-----\nMBgCEQC+xlMZRSu5W1fw4DqAlk9NAgMBAAE=\n-----END RSA PUBLIC KEY-----\n'
SERVER_PRIVATE_KEY = u'-----BEGIN RSA PRIVATE KEY-----\nMGMCAQACEQC+xlMZRSu5W1fw4DqAlk9NAgMBAAECEQCPMT9YXWH3QO6GkB0gF/fh\nAgkOZpsvl0rA1wkCCA0/XFIWCSMlAgkD7XQRrL+UjJECCANIlSVzeMhRAgkJBkIV\nBvuNBEA=\n-----END RSA PRIVATE KEY-----\n'
